version: "3"

services:
  app:
    container_name: app
    build: .
    depends_on:
      - "database"
    ports:
      - "3001:3001"

  database:
    container_name: mongo
    image: mongo:latest
    expose: 
      - "27017"